# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.announce-bot: debug

announce-bot:
  sensors:
    - binary_sensor.g4_pro_motion_3
  openai_key: !secret openai_key